** defs
*** Docker Registry
- A *Docker Registry* is the remote location where Docker Images are
  stored. You push images to a registry and pull images from a
  registry. You can host your own registry or use a provider’s
  registry. For example, AWS and Google Cloud have registries.

*** Docker Hub
- Docker Hub is the largest registry of Docker images. It’s also the
  default registry. You can find images and store your own images on
  Docker Hub for free.
*** Docker Repository
- A Docker Repository is a collection of Docker images with the same
  name and different tags. The tag is the identifier for the image.
- Usually a repository has different versions of the same image. For
  example, Python is the name of the most popular official Docker
  image repository on Docker Hub. Python:3.7-slim refers to the
  version of the image with the 3.7-slim tag in the Python
  repository. You can push a repository or a single image to a
  registry.

** CLI
- Recall that a Docker image is made of a Dockerfile + any necessary
  dependencies. Also recall that a Docker container is a Docker image
  brought to life. To work with Docker commands, you first need to
  know whether you’re dealing with an image or a container.
  + A Docker image either exists or it doesn’t.
  + A Docker container either exists or it doesn’t.
  + A Docker container that exists is either running or it isn’t.

- A command referring to a specific container or image requires the
  name or id of that container or image.
*** container
- Create a container from an image.
  #+BEGIN_SRC
  docker container create my_repo/my_image:my_tag
  #+END_SRC
- Start an existing container
  #+BEGIN_SRC
  docker container start my_container
  #+END_SRC
- Create a new container and start it
  #+BEGIN_SRC
  docker container run my_image
  #+END_SRC
*** Images
- Build a Docker image named my_image from the Dockerfile located at the specified path or URL
  #+BEGIN_SRC
  docker image build -t my_repo/my_image:my_tag .
  #+END_SRC
  + The ~.~ (period) at the end of the command tells Docker to build the
    image according to the Dockerfile in the current working
    directory.
- Push an image to a registry.
  #+BEGIN_SRC
  docker image push my_repo/my_image:my_tag
  #+END_SRC
- List your images. Shows you the size of each image, too.
  #+BEGIN_SRC
  docker image ls
  #+END_SRC
- Display an image’s intermediate images with sizes and how they were created.
  #+BEGIN_SRC
  docker image history my_image
  #+END_SRC
-




**** Summary
- Use ~docker container my_command~
  + create — Create a container from an image.
  + start — Start an existing container.
  + run — Create a new container and start it.
  + ls — List running containers.
  + inspect — See lots of info about a container.
  + logs — Print logs.
  + stop — Gracefully stop running container.
  + kill —Stop main process in container abruptly.
  + rm — Delete a stopped container.
- Use ~docker image my_command~
  + build — Build an image.
  + push — Push an image to a remote registry.
  + ls — List images.
  + history — See intermediate image info.
  + inspect — See lots of info about an image, including the layers.
  + rm — Delete an image.
- Misc
- docker version — List info about your Docker Client and Server versions.
- docker login — Log in to a Docker registry.
- docker system prune — Delete all unused containers, unused networks, and dangling images.

** Volumes
- Two Types
  + Persistent: will be available on the host, when the container goes
    away, the data still will be there
  + Ephemeral: will exist as long as a container is using them
+ They are not part of images
*** Sharing data with the host
- share a directory
  #+BEGIN_SRC
  docker run -it -v /home/farhad/play/docker/foobar:/shared_stuff ubuntu bash
  #+END_SRC
  the data will be preserved
- share a file
  #+BEGIN_SRC
  docker run -it -v /home/farhad/play/dock/foobar/blah:/the_foo ubuntu bash
  #+END_SRC
*** sharing between containers
-
  #+BEGIN_SRC sh
  # a
  docker run -it --name foobar -v /shared_data ubuntu bash


  # b
  docker run -it --volumes-from foobar ubuntu bash
  #+END_SRC
** Dockefile command
*** RUN
 - RUN creates a layer at build-time. Docker commits the state of the
   image after each RUN.
 - RUN is often used to install packages into an image. For example,
  ~RUN apk update && apk upgrade && apk add bash~
 - ~RUN~, ~CMD~ and ~ENTRYPOINT~ can be used in exec form
   or shell form. Exec form uses JSON array syntax like so:
   ~RUN ["my_executable", "my_first_param1", "my_second_param2"]~.

*** COPY
- The ~COPY . ./app~ instruction tells Docker to take the files and
  folders in your local build context and add them to the Docker
  image’s current working directory. Copy will create the target
  directory if it doesn’t exist.

*** ADD
- ADD does the same thing as COPY, but has two more use cases. ADD can
  be used to move files from a remote URL to a container and ADD can
  extract local TAR files.

*** CMD
- CMD provides Docker a command to run when a container is started. It
  does not commit the result of the command to the image at build
  time.
- Only one CMD instruction per Dockerfile. Otherwise all but the final
  one are ignored.
- CMD can include an executable. If CMD is present without an
  executable, then an ENTRYPOINT instruction must exist. In that case,
  both CMD and ENTRYPOINT instructions should be in JSON format.
- Command line arguments to ~docker run~ override arguments provided to
  CMD in the Dockerfile.

*** WORKDIR
- WORKDIR changes the working directory in the container for the COPY,
  ADD, RUN, CMD, and ENTRYPOINT instructions that follow it. A few
  notes:
- It’s preferable to set an absolute path with WORKDIR rather than
  navigate through the file system with cd commands in the Dockerfile.
- WORKDIR creates the directory automatically if it doesn’t exist.
- You can use multiple WORKDIR instructions. If relative paths are
  provided, then each WORKDIR instruction changes the current working
  directory.

*** ENTRYPOINT
- The ENTRYPOINT instruction also allows you provide a default command
  and arguments when a container starts. It looks similar to CMD, but
  ENTRYPOINT parameters are not overwritten if a container is run with
  command line parameters.
- Instead, command line arguments passed to ~docker run my_image_name~
  are appended to the ENTRYPOINT instruction’s arguments. For example,
  ~docker run my_image~ bash adds the argument bash to the end of the
  ENTRYPOINT instruction’s existing arguments.
- A Dockerfile should have at least one CMD or ENTRYPOINT instruction.

- A Dockerfile should have at least one CMD or ENTRYPOINT instruction.

- The [[https://docs.docker.com/v17.09/engine/reference/builder/#understand-how-cmd-and-entrypoint-interact][Docker docs]] have a few suggestions for choosing between CMD and
  ENTRYPOINT for your initial container command:
  + Favor ENTRYPOINT when you need to run the same command every time.
  + Favor ENTRYPOINT when a container will be used as an executable
    program.
  + Favor CMD when you need to provide extra default arguments that
    could be overwritten from the command line.
*** VOLUME
- VOLUME specifies where your container will store and/or access
  persistent data.
*** ENV
-
  #+BEGIN_SRC
  ENV <key> <value>
  ENV <key>=<value> ...
  #+END_SRC
- The ENV instruction sets the environment variable <key> to the value
  <value>. This value will be in the environment for all subsequent
  instructions in the build stage and can be replaced inline in many
  as well.

** Caching
- When building an image, Docker steps through the instructions in
  your Dockerfile, executing each in order. As each instruction is
  examined, Docker looks for an existing intermediate image in its
  cache that it can reuse instead of creating a new (duplicate)
  intermediate image.

** List Docker CLI commands
- docker
- docker container --help

** Display Docker version and info
- docker --version
- docker version
- docker info

** Execute Docker image
- docker run hello-world

** List Docker images
- docker image ls

** List Docker containers (running, all, all in quiet mode)
- docker container ls
- docker container ls --all
- docker container ls -aq

** A Dozen Dockerfile Instructions
- ~FROM~
  + specifies the base (parent) image.
- ~LABEL~
  + provides metadata. Good place to include maintainer info.
- ~ENV~
  + sets a persistent environment variable.
- ~RUN~
  + runs a command and creates an image layer. Used to install packages into containers.
- ~COPY~
  + copies files and directories to the container.
- ~ADD~
  + copies files and directories to the container. Can upack local .tar files.
- ~CMD~
  + provides a command and arguments for an executing container. Parameters can be overridden. There can be only one CMD.
- ~WORKDIR~
  + sets the working directory for the instructions that follow.
- ~ARG~
  + defines a variable to pass to Docker at build-time.
- ~ENTRYPOINT~
  + provides command and arguments for an executing container. Arguments persist.
- ~EXPOSE~
  + exposes a port.
- ~VOLUME~
  + creates a directory mount point to access and store persistent data.

** Misc
#+BEGIN_SRC sh
  docker build -t friendlyhello .  # Create image using this directory's Dockerfile

  docker run -p 4000:80 friendlyhello  # Run "friendlyhello" mapping port 4000 to 80

  docker run -d -p 4000:80 friendlyhello         # Same thing, but in detached mode

  docker container ls                                # List all running containers

  docker container ls -a             # List all containers, even those not running

  docker container stop <hash>           # Gracefully stop the specified container

  docker container kill <hash>         # Force shutdown of the specified container

  docker container rm <hash>        # Remove specified container from this machine

  docker container rm $(docker container ls -a -q)         # Remove all containers

  docker container prune                                   # To remove all stopped containers

  docker image ls -a                             # List all images on this machine

  docker image rm <image id>            # Remove specified image from this machine

  docker image rm $(docker image ls -a -q)   # Remove all images from this machine


  docker login             # Log in this CLI session using your Docker credentials

  docker image tag <image> username/repository:tag  # Tag <image> for upload to registry, if you don't want to publish to registry you can use foo:bar as a tag

  docker push username/repository:tag            # Upload tagged image to registry

  docker run username/repository:tag                   # Run image from a registry
#+END_SRC
** CheatSheet
- [[https://kapeli.com/cheat_sheets/Dockerfile.docset/Contents/Resources/Documents/index][here]]
- [[https://towardsdatascience.com/15-docker-commands-you-should-know-970ea5203421][here]]
** sample
-
  #+BEGIN_SRC
  docker build -t react-example .
  #+END_SRC
-
  #+BEGIN_SRC
  docker run -d -it -v ${PWD}:/usr/src/app -v /usr/src/app/node_modules -p 3000:3000 --rm react-example
  #+END_SRC
-
  #+BEGIN_SRC
  docker exec -it 04869dd4177c bash
  #+END_SRC
- get the id of the last started container
  #+BEGIN_SRC
  docker ps -n 1 --format "{{.ID}}"
  #+END_SRC
