* On Wrting Well
Bunch of quotes from aforementioned book

*** Introduction
 1. same decisions that confront every writer going in search of his
    or her past: matters of selection, reduction, organization and
    tone.
** Principles
*** The Transaction
 1. rewrite what they have rewritten
 2. “Do you put symbolism in your writing?” a student asked me.  “Not
    if I can help it,” I replied. I have an unbroken record of missing
    the deeper meaning in any story, play or movie, and as for dance
    and mime, I have never had any idea of what is being conveyed.
 3. Clutter is the disease of American writing.
 4. But the secret of good writing is to strip every sentence to its
    cleanest components. Every word that serves no function, every
    long word that could be a short word, every adverb that carries
    the same meaning that’s already in the verb, every passive
    construction that leaves the reader unsure of who is doing what.
 5. It’s impossible for a muddy thinker to write good English. He may
    get away with it for a paragraph or two, but soon the reader will
    be lost, and there’s no sin so grave, for the reader will not
    easily be lured back.
 6. If the reader is lost, it’s usually because the writer hasn’t been
    careful enough.  That carelessness can take any number of
    forms. Perhaps a sentence is so excessively cluttered that the
    reader, hacking through the verbiage, simply doesn’t know what it
    means.  Perhaps a sentence has been so shoddily constructed that
    the reader could read it in several ways. Perhaps the writer has
    switched pronouns in midsentence, or has switched tenses, so the
    reader loses track of who is talking or when the action took
    place. Perhaps Sentence B is not a logical sequel to Sentence A;
    the writer, in whose head the connection is clear, hasn’t bothered
    to provide the missing link. Perhaps the writer has used a word
    incorrectly by not taking the trouble to look it up.
 7. Writers must therefore constantly ask: what am I trying to say?
    Surprisingly often they don’t know. Then they must look at what
    they have written and ask: have I said it? Is it clear to someone
    encountering the subject for the first time? If it’s not, some
    fuzz has worked its way into the machinery. The clear writer is
    someone clearheaded enough to see this stuff for what it is: fuzz.
*** Clutter
 1. Examine every word you put on paper. You’ll find a surprising
    number that don’t serve any purpose.
 2. Beware, then, of the long word that’s no better than the short
    word: “assistance” (help), “numerous” (many), “facilitate” (ease),
    “individual” (man or woman), “remainder” (rest), “initial”
    (first), “implement” (do), “sufficient” (enough), “attempt” (try),
    “referred to as” (called) and hundreds more.
 3. “with the possible exception of” (except), “due to the fact that”
    (because), “he totally lacked the ability to” (he couldn’t),
    “until such time as” (until), “for the purpose of” (for).
 4. Most first drafts can be cut by 50 percent without losing any
    information or losing the author’s voice.
 5. Look for the clutter in your writing and prune it ruthlessly.  Be
    grateful for everything you can throw away. Reexamine each
    sentence you put on paper.  Is every word doing new work? Can any
    thought be expressed with more economy? Is anything pompous or
    pretentious or faddish? Are you hanging on to something useless
    just because you think it’s beautiful? Simplify, simplify.
 6. This is the problem of writers who set out deliberately to garnish
    their prose. You lose whatever it is that makes you unique. The
    reader will notice if you are putting on airs.  Readers want the
    person who is talking to them to sound genuine. Therefore a
    fundamental rule is: be yourself.
 7.     Assume that you are the writer sitting down to write. You
    think your article must be of a certain length or it won’t seem
    important. You think how august it will look in print. You think
    of all the people who will read it. You think that it must have
    the solid weight of authority. You think that its style must
    dazzle. No wonder you tighten; you are so busy thinking of your
    awesome responsibility to the finished article that you can’t even
    start. Yet you vow to be worthy of the task, and, casting about
    for grand phrases that wouldn’t occur to you if you weren’t trying
    so hard to make an impression, you plunge in.
*** The Audience
 1. Soon after you confront the matter of preserving your identity,
    another question will occur to you: “Who am I writing for?”  It’s
    a fundamental question, and it has a fundamental answer: You are
    writing for yourself.  Don’t try to visualize the great mass
    audience. There is no such audience—every reader is a different
    person. Don’t try to guess what sort of thing editors want to
    publish or what you think the country is in a mood to
    read. Editors and readers don’t know what they want to read until
    they read it. Besides, they’re always looking for something new.
 2. If you’re not a person who says “indeed” or “moreover,” or who
    calls someone an individual (“he’s a fine individual”), please
    don’t write it.

*** Words

 1. What is “journalese”? It’s a quilt of instant words patched
    together out of other parts of spe ech. Adjectives are used as
    nouns (“greats,” “notables”). Nouns are used as verbs (“to host”),
    or they are chopped off to form verbs (“enthuse,” “emote”), or
    they are padded to form verbs (“beef up,” “put teeth into”). This
    is a world where eminent people are “famed” and their associates
    are “staffers,” where the future is always “upcoming” and someone
    is forever “firing off” a note. Nobody in America has sent a note
    or a memo or a telegram in years. Famed diplomat Condoleezza Rice,
    who hosts foreign notables to beef up the morale of top State
    Department staffers, sits down and fires off a lot of notes. Notes
    that are fired off are always fired in anger and from a sitting
    position. What the weapon is I’ve never found out.

 2. The race in writing is not to the swift but to the original.

 3. Such considerations of sound and rhythm should go into everything
    you write. If all your sentences move at the same plodding gait,
    which even you recognize as deadly but don’t know how to cure,
    read them aloud. (I write entirely by ear and read everything
    aloud before letting it go out into the world.) You’ll begin to
    hear where the trouble lies. See if you can gain variety by
    reversing the order of a sentence, or by substituting a word that
    has freshness or oddity, or by altering the length of your
    sentences so they don’t all sound as if they came out of the same
    machine. An occasional short sentence can carry a tremendous
    punch. It stays in the reader’s ear.  Remember that words are the
    only tools you’ve got. Learn to use them with originality and
    care. And also remember: somebody out there is listening.

*** Usage
 1.  “I choose always the grammatical form unless it sounds affected,”
    Marianne Moore

** Methods
*** Unity 
1. You learn to write by writing. It’s a truism, but what makes it a
   truism is that it’s true. The only way to learn to write is to
   force yourself to produce a certain number of words on a regular
   basis.
2. One choice is unity of *pronoun*. Are you going to write in the
   first person, as a participant, or in the third person, as an
   observer?  Or even in the second person, that darling o f
   sportswriters hung up on Hemingway? (“You knew this had to be the
   most spine-tingling clash of giants you’d ever seen from a pressbox
   seat, and you weren’t just some green kid who was still wet behind
   the ears.”)
3. Unity of *tense* is another choice. You must choose the tense in
   which you are principally going to address the reader, no matter
   how many glances you may take backward or forward along the way.
4. Another choice is unity of *mood*. You might want to talk to the
   reader in the casual voice that The New Yorker has strenuously
   refined. Or you might want to approach the reader with a certain
   formality to describe a serious event or to present a set of
   important facts.  Both tones are acceptable. In fact, any tone is
   acceptable. But don’t mix two or three.
5. Therefore ask yourself some basic questions before you start. For
   example: “In what capacity am I going to address the reader?”
   (Reporter? Provider of information? Average man or woman?) “What
   pronoun and tense am I going to use?” “What style?” (Impersonal
   reportorial? Personal but formal? Personal and casual?) “What
   attitude am I going to take toward the material?” (Involved?
   Detached? Judgmental? Ironic? Amused?) “How much do I want to
   cover?” “What one point do I want to make?”
6. Nobody can write a book or an article “about” something. Tolstoy
   couldn’t write a book about war and peace, or Melville a book about
   whaling. They made certain reductive decisions about time and place
   and about individual characters in that time and place—one man
   pursuing one whale.  *Every writing project must* *be reduced
   before you start to write.*
7. As for what point you want to make, every successful piece of
   nonfiction should leave the reader with one provocative thought
   that he or she didn’t have before. Not two thoughts, or five—just
   one. So decide what single point you want to leave in the reader’s
   mind.

*** The Lead and the Ending
1. The most important sentence in any article is the first one. If it
   doesn’t induce the reader to proceed to the second sentence, your
   article is dead. And if the second sentence doesn’t induce him to
   continue to the third sentence, it’s equally dead. Of such a
   progression of sentences, each tugging the reader forward until he
   is hooked, a writer constructs that fateful unit, the “lead.”
2. I urge you not to count on the reader to stick around.  Readers
   want to know—very soon—what’s in it for them. Therefore your lead
   must capture the reader immediately and force him to keep
   reading. It must cajole him with freshness, or novelty, or paradox,
   or humor, or surprise, or with an unusual idea, or an interesting
   fact, or a question. Anything will do, as long as it nudges his
   curiosity and tugs at his sleeve.
3. The perfect ending should take your readers slightly by surprise
   and yet seem exactly right.  They didn’t expect the article to end
   so soon, or so abruptly, or to say what it said. But they know it
   when they see it. Like a good lead, it works. It’s like the curtain
   line in a theatrical comedy. We are in the middle of a scene (we
   think), when suddenly one of the actors says something funny, or
   outrageous, or epigrammatic, and the lights go out. We are startled
   to find the scene over, and then delighted by the aptness of how it
   ended. What delights us is the playwright’s perfect control.
4. How could it not be a perfect ending? Surprise is the most
   refreshing element in nonfiction writing. If something surprises
   you it will also surprise—and delight the people you are writing
   for, especially as you conclude your story and send them on their
   way.
*** Bits & Pieces
1. Use active verbs unless there is no comfortable way to get around
   using a passive verb. The difference between an activeverb style
   and a passive-verb style—in clarity and vigor—is the difference
   between life and death for a writer.
2. I use “perpetrated” because it’s the kind of word that
   passive-voice writers are fond of. They prefer long words of Latin
   origin to short Anglo-Saxon words—which compounds their trouble and
   makes their sentences still more glutinous. Short is better than
   long. Of the 701 words in Lincoln’s Second Inaugural Address, a
   marvel of economy in itself, 505 are words of one syllable and 122
   are words of two syllables.
3. Most adverbs are unnecessary. You will clutter your sentence and
   annoy the reader if you choose a verb that has a specific meaning
   and then add an adverb that carries the same meaning. Don’t tell us
   that the radio blared loudly; “blare” connotes loudness.
4. Most adjectives are also unnecessary. Like adverbs, they are
   sprinkled into sentences by writers who don’t stop to think that
   the concept is already in the noun. This kind of prose is littered
   with precipitous cliffs and lacy spiderwebs, or with adjectives
   denoting the color of an object whose color is well known: yellow
   daffodils and brownish dirt.
5. Prune out the small words that qualify how you feel and how you
   think and what you saw: “abit,” “a little,” “sort of,” “kind of,”
   “rather,” “quite,” “very,” “too,” “pretty much,” “in asense” and
   dozens more. They dilute your style and your persuasiveness.
6. The large point is one of authority. Every little qualifier
   whittles away some fraction of the reader’s trust. Readers want a
   writer who believes in himself and in what he is saying. Don’t
   diminish that belief. Don’t be kind of bold. Be bold.
7. The Period. There’s not much to be said about the period except
   that most writers don’t reach it soon enough.
8. Humor is best achieved by understatement, and there’s nothing
   subtle about an exclamation point.
9. *The Dash*. Somehow this invaluable tool is widely regarded as not
   quite proper—a bumpkin at the genteel dinner table of good
   English. But it has full membership and will get you out of many
   tight corners. The dash is used in two ways. One is to amplify or
   justify in the second part of the sentence a thought you stated in
   the first part. “We decided to keep going—it was only 100 miles
   more and we could get there in time for dinner.” By its veryshape
   the dash pushes the sentence ahead and explains why they decided to
   keep going.  The other use involves two dashes, which set apart a
   parenthetical thought within a longer sentence. “She told me to get
   in the car—she had been after me all summer to have a haircut—and
   we drove silently into town.” An explanatory detail that might
   otherwise have required a separate sentence is neatly dispatched
   along the way.
10. Learn to alert the reader as soon as possible to any change in
    mood from the previous sentence. At least a dozen words will do
    this job for you: “but,” “yet,” “however,” “nevertheless,”
    “still,” “instead,” “thus,” “therefore,” “meanwhile,” “now,”
    “later,” “today,” “subsequently” and several more. I can’t
    overstate how much easier it is for readers to process a sentence
    if you start with “but” when you’re shifting direction. Or,
    conversely, how much harder it is if they must wait until the end
    to realize that you have shifted.
11. If your sentence needs a comma to achieve its precise meaning, it
    probably needs “which.”  “Which” serves a particular identifying
    function, different from “that.” (A) “Take the shoes that are in
    the closet.” This means: take the shoes that are in the closet,
    not the ones under the bed. (B) “Take the shoes, which are in the
    closet.” Only one pair of shoes is under discussion; the “which”
    usage tells you where they are. Note that the comma is necessary
    in B, but not in A.
12. Nouns that express a concept are commonly used in bad writing
    instead of verbs that tell what somebody did.
13. Don’t overstate.
14. Rewriting is the essence of writing well: it’s where the game is
    won or lost. That idea is hard to accept. We all have an emotional
    equity in our first draft; we can’t believe that it wasn’t born
    perfect. But the odds are close to 100 percent that it
    wasn’t. Most writers don’t initially say what they want to say, or
    say it as well as they could. The newly hatched sentence almost
    always has something wrong with it. It’s not clear. It’s not
    logical. It’s verbose. It’s klunky. It’s pretentious. It’s
    boring. It’s full of clutter. It’s full of clichés. It lacks
    rhythm. It can be read in several different ways. It doesn’t lead
    out of the previous sentence. It doesn’t ...  The point is that
    clear writing is the result of a lot of tinkering.
15. Keep putting yourself in the reader’s place. Is there something he
    should have been told early in the sentence that you put near the
    end? Does he know when he starts sentence B that you’ve made a
    shift—of *subject*, *tense*, *tone*, emphasis—from sentence A?
16. Much could still be done in such areas as *cadence*, detail and
    freshness of language. The total construction is equally
    important. Read your article aloud from beginning to end, always
    remembering where you left the reader in the previous sentence.
17. The reader plays a major role in the act of writing and must be
    given room to play it. Don’t annoy your readers by
    over-explaining—by telling them something they already know or can
    figure out. Try not to use words like “surprisingly,”
    “predictably” and “of course,” which put a value on a fact before
    the reader encounters the fact. Trust your material.

*** Writing About People
